swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger codetest"
  termsOfService: ""
  contact:
    email: "xj0.drew@gmail.com"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /api/cheese:
    get:
      tags:
      - "cheese"
      summary: "List all cheeses"
      description: ""
      operationId: "getCheese"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Get the list of cheeses"
        required: true
        schema:
          $ref: "#/definitions/CheeseList"
      responses:
        "405":
          description: "Invalid input"


  /api/cheeseorder:
    get:
      tags:
      - "cheeseorder"
      summary: "returns the current cheese order"
      description: "Returns a list of cheeses and the amounts wanted"
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
  /api/cheeseorder:
    post:
      tags:
      - "cheeseorder"
      summary: ""
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the cheese"
        required: true
        schema:
          $ref: "#/definitions/CheeseOrder"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CheeseOrder"
        "400":
          description: "Invalid Order"
  /api/cheeseorder/update:
    post:
      tags:
      - "cheeseorder"
      summary: "Update the order by adding a cheese"
      description: ""
      operationId: "Update"
      produces:
      - "application/json"
      parameters:
      - name: "cheeseOrder"
        in: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/CheeseList"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CheeseOrder"
        "400":
          description: "Invalid data supplied"
        "404":
          description: "Order not found"
  /api/cheeseorder/delete:
    post:
      tags:
      - "cheeseorder"
      summary: "Delete item from order"
      description: "Delete a cheese from the order"
      operationId: "deleteOrder"
      produces:
      - "application/json"
      parameters:
      - name: "cheeseOrder"
        in: "body"
        description: "copy of the order that needs to be deleted"
        required: true
        type: "cheeseOrder"
        schema:
          $ref: "#/definitions/CheeseList"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"

definitions:
  CheeseOrder:
    type: "object"
    properties:
      Id:
        type: "string"
        format: "guid"
      Date:
        type: "string"
        format: "date-time"
      cheeseList:
        type: "array"
        items: {}
    xml:
      name: "CheeseOrder"
  CheeseList:
    type: "array"
    items:
      $ref: '#/definitions/Cheese'
    xml:
      name: "CheeseList"
  Cheese:
    type: "object"
    properties:
      Id:
        type: "string"
        format: "guid"
      Colour:
        type: "string"
        format: "guid"
      Image:
        type: "string"
        format: "guid"
      Name:
        type: "string"
        format: "guid"
      Descripton:
        type: "string"
        format: "guid"
      PricePerKilo:
        type: "number"
        format: "double"
      Cost:
        type: "number"
        format: "double"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"